packages = [
    'argparse',
    'benchmark',
    'catch2',
    'fmt',
    'glm',
    'ms-gsl',
    'nlohmann-json',
    'range-v3',
    'reproc',
    'spdlog',
    'tbb',
    'tinygltf',
    'zlib',
]
export = 'artifacts'
